### ISSUE TITLE
OrdersController#get_estimated_price (NoMethodError) "undefined method `jkasdasdhsakjdhaksjhdjksahdkjashdkhasdkjhsakdjhsakjdhkashdkshadjksahdjsakhdajkshkjdhaskjdhaskjhdkjashdkjsahdjkshdkjhdajkdhsajkdhasjkdhsajkdhjskahdkjashsadkjhsjkfree_waiting_mins' for nil:NilClass"

### ISSUE THREAD

**Issue by no-reply-porter** [shubhamgupta731/dictionary#4]
<table><tr><th>Exception</th><td>undefined method `jkasdasdhsakjdhaksjhdjksahdkjashdkhasdkjhsakdjhsakjdhkashdkshadjksahdjsakhdajkshkjdhaskjdhaskjhdkjashdkjsahdjkshdkjhdajkdhsajkdhasjkdhsajkdhjskahdkjashsadkjhsjkfree_waiting_mins&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>August 05, 2015 16:58:27 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/shubhamgupta731/dictionary/blob/af867932ebac3802188f3a294c1649b4fe114696/app/models/order.rb#L937'>[app].../app/models/order.rb:937:in `estimate_fare'</a>
<a href='https://github.com/shubhamgupta731/dictionary/blob/af867932ebac3802188f3a294c1649b4fe114696/app/controllers/orders_controller.rb#L133'>[app].../app/controllers/orders_controller.rb:133:in `block in get_estimated_price'</a>
<a href='https://github.com/shubhamgupta731/dictionary/blob/af867932ebac3802188f3a294c1649b4fe114696/app/controllers/orders_controller.rb#L130'>[app].../app/controllers/orders_controller.rb:130:in `each'</a>
<a href='https://github.com/shubhamgupta731/dictionary/blob/af867932ebac3802188f3a294c1649b4fe114696/app/controllers/orders_controller.rb#L130'>[app].../app/controllers/orders_controller.rb:130:in `get_estimated_price'</a>
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.2/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:149:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:229:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:299:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:299:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:447:in `public_send'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:447:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:298:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:298:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:86:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[bundle].../gems/activesupport-4.1.2/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.2/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.2/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.2/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.2/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/journey/router.rb:71:in `block in call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/routing/route_set.rb:678:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../bundler/gems/party_foul-0b4e3deb8cec/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/deflater.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-4.1.2/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-4.1.2/lib/active_record/migration.rb:380:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/web-console-2.2.1/lib/web_console/middleware.rb:39:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-4.1.2/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.2/lib/rails/rack/logger.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activesupport-4.1.2/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.1.2/lib/action_dispatch/middleware/static.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-4.1.2/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.2/lib/rails/application.rb:144:in `call'
[bundle].../gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/handler/webrick.rb:60:in `service'
/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'</pre>

Fingerprint: `7f19dd4491a03efc6e2d99a670ae2b20d278ea2e`

**Comment by no-reply-porter** [comment]
<table><tr><th>Occurred At</th><td>August 05, 2015 16:58:27 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/orders/get_estimated_price?order%5Bgeo_region_id%5D=1&amp;order%5Bvehicle_id%5D=4&amp;order%5Bis_return%5D=0&amp;order%5Bis_premium%5D=0&amp;order%5Bestimated_distance%5D=26&amp;order%5Bestimated_travel_duration%5D=61&amp;order%5Bn_waypoints%5D=0&amp;order%5Bstart_time%5D=2015%2F08%2F06+09%3A15&amp;geocode_results%5B0%5D%5B%5D=&amp;geocode_results%5B0%5D%5B%5D=&amp;geocode_results%5B1%5D%5B%5D=&amp;geocode_results%5B1%5D%5B%5D=&amp;geocode_results%5B2%5D%5B%5D=&amp;geocode_results%5B2%5D%5B%5D=&amp;geocode_results%5B3%5D%5B%5D=&amp;geocode_results%5B3%5D%5B%5D=&amp;geocode_results%5B4%5D%5B%5D=&amp;geocode_results%5B4%5D%5B%5D=&amp;geocode_results%5B5%5D%5B%5D=&amp;geocode_results%5B5%5D%5B%5D=&amp;geocode_results%5B6%5D%5B%5D=&amp;geocode_results%5B6%5D%5B%5D=&amp;geocode_results%5B7%5D%5B%5D=&amp;geocode_results%5B7%5D%5B%5D=&amp;geocode_results%5B8%5D%5B%5D=&amp;geocode_results%5B8%5D%5B%5D=&amp;geocode_results%5B9%5D%5B%5D=&amp;geocode_results%5B9%5D%5B%5D=&amp;duration_arr%5B%5D=57&amp;duration_arr%5B%5D=690&amp;duration_arr%5B%5D=494&amp;duration_arr%5B%5D=753&amp;duration_arr%5B%5D=485&amp;duration_arr%5B%5D=248&amp;duration_arr%5B%5D=398&amp;duration_arr%5B%5D=525&amp;vehicle_id=4</td></tr><tr><th>Params</th><td><table><tr><th>order</th><td><table><tr><th>geo_region_id</th><td>1</td></tr><tr><th>vehicle_id</th><td>4</td></tr><tr><th>is_return</th><td>0</td></tr><tr><th>is_premium</th><td>0</td></tr><tr><th>estimated_distance</th><td>26</td></tr><tr><th>estimated_travel_duration</th><td>61</td></tr><tr><th>n_waypoints</th><td>0</td></tr><tr><th>start_time</th><td>2015/08/06 09:15</td></tr></table></td></tr><tr><th>geocode_results</th><td><table><tr><th>0</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>1</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>2</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>3</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>4</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>5</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>6</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>7</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>8</th><td>[&quot;&quot;, &quot;&quot;]</td></tr><tr><th>9</th><td>[&quot;&quot;, &quot;&quot;]</td></tr></table></td></tr><tr><th>duration_arr</th><td>[&quot;57&quot;, &quot;690&quot;, &quot;494&quot;, &quot;753&quot;, &quot;485&quot;, &quot;248&quot;, &quot;398&quot;, &quot;525&quot;]</td></tr><tr><th>vehicle_id</th><td>4</td></tr><tr><th>controller</th><td>orders</td></tr><tr><th>action</th><td>get_estimated_price</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>29339fed304e95b4ae93d00fef4ba71d</td></tr><tr><th>administrator_return_to</th><td>/administrators/unknown_caller</td></tr><tr><th>warden.user.administrator.key</th><td>[[18], &quot;$2a$10$uv4QhqCRaS0QeREQtJ2y5u&quot;]</td></tr><tr><th>_csrf_token</th><td>HGQTAYFdTYXg/PoKisgyAQAbwlCg6HbGVrGswQiJNts=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
